### PR TITLE
Adds emotion support

### LINKED ISSUE #57: [RFC] Pluggable styling API
## What

I propose to establishing a support for different CSS-in-JS libraries to help developers take benefits of Atomic Layout using their favorite styling solution.

## Why

* The library operates on CSS properties Object, which can be computed into string (when needed), and be compliant with about any modern CiJ solution

## Implementation

To enable such support it has been decided to convert the library to a monorepo that consist of the following parts:

- core library (`@atomic-layout/core`, responsible for media queries calculation, areas parsing, parametric components generation without attachment to any specific styling/rendering solution)
- rendering libraries (i.e. `@atomic-layout/emotion`)

All rendering libraries would list `@atomic-layout/core` as a dependency and utilize functions and types the core library exports.

## Usage

To use Atomic Layout with another styling solution (implying that such solution is supported) import the respective `@atomic-layout/X` package and use it with the same API described in the documentation:

```jsx
import React from 'react'
import { Composition } from '@atomic-layout/emotion'

const MyComponent = () => (
  <Composition templateCols="250px 1fr">
    <span>Emotion support</span>
    <span>Example</span>
  </Composition>
)
```

### PR DESCRIPTION
**Pull request by kettanaito**
## Architecture & Configuration

- [x] Adds a new `@atomic-layout/emotion` package
- [x] Configure unit tests
- [x] Configure Storybook for E2E testing
  - [x] For CJS build
  - [x] For UMD build
  - [x] For ESM build

## Build

- [x] CJS
- [x] UMD
- [x] ESM
- [x] Properly list `@emotion/core` and `@emotion/styled` as globals in Rollup config
- [x] Generate TypeScript type definitions properly

## Implementation

- [x] Resolve `Only` component, because it imports relative `Box` from the `atomic-layout`
- [x] Implement `Visible` component
- [x] Consider reusing `atomic-layout` entirely, because of the Babel plugin transforming the imports from `styled-components` to `@emotion/styled`. There is little motivation to keep some separate implementations (copies) of components by default.

## Testing

- [x] Reuse existing E2E test scenarios
- [x] Ensure E2E tests pass
  - [x] Fix styles override issue (`Box` does not allow `display` property override from `applyStyles`):

```
1) Components Box Supports CSS properties overrides:
     CypressError: Timed out retrying: expected '<div#box.sc-ifAKCX.cikOGB.css-16r01mf>' to have CSS property 'display' with the value 'table', but the value was 'block'

2) Semantics Polymorphic prop When given a custom React component Overrides layout styles:
     CypressError: Timed out retrying: expected '<header#header.sc-htoDjs.kFljPQ.css-1vgwltm>' to have CSS property 'display' with the value 'block', but the value was 'flex'
```

## DX

- [x] Add `@atomic-layout/emotion` readme
- [x] Update the main README to reference `@atomic-layout/emotion` implementation

## Nice to have

- [x] Move Babel config, Storybook config and examples to the root level
- [ ] Remove the Storybook `include` workaround for `babel-loader` (https://github.com/storybookjs/storybook/issues/3346)

## GitHub

- Successor to #261 
- Relates to #122 
- Closes #57 

## Release version

- [ ] patch (internal improvements)
- [x] minor (backward-compatible changes)
- [ ] major (breaking, backward-incompatible changes)

## Contributor's checklist

- [x] My branch is up-to-date with the latest `master`
- [x] I ran `yarn verify` and verified the build and tests passing

### CODE REVIEW

**Comment by bitttttten** [comment]
Very cool! Happy to test if you want to publish it to beta.

**Comment by kettanaito** [comment]
@bitttttten Absolutely! Thank you. At the moment I'm in the middle of gardening the internals so they won't get too duplicated while still allowing customizations on the rendering (styling) ends. Thinking of making Storybook accept an Atomic Layout build module via environmental variables so it can include even versions built with different styling solutions within a single monorepo.

Overall, no estimates how fast I can land this, but at least the roadmap is clear.

**Comment by kettanaito** [comment]
Performed a stub of `@atomic-layout/emotion` in the existing stories and _it worked_! Continue on making E2E testing parametric by providing a relative build module path.

**Comment by kettanaito** [comment]
# Parametric Storybook builds

This pull request reworks Storybook configuration to accept parametric builds. By providing environmental variables that point to the package (as in "monorepo package") and build target (cjs/umd/esm) Storybook is able to resolve the build module and alias `atomic-layout` imports to that module.

## Issue: Storybook includes `cwd` only

During the development I've encountered that Storybook's webpack configuration has an explicit `include` property on `babel-loader` that includes CWD only. This means that if stories directory lies outside than CWD it **won't get transpiled by `babel-loader`** at all.

Currently I've introduced a workaround by manually iterating over Storybook's webpack configuration and appending examples (stories) directory to the `include` array. Ideally, this would need to be addressed by Storybook.

**Comment by kettanaito** [comment]
# Parametric Cypress runs

Much similar to the parametric Storybook builds, Cypress will now accept the `package` environmental variable that points to the package subjected to testing. I've used `{PACKAGE}` placeholder in `cypress.json@fileServerBase` to be replaced with the environmental variable for path resolving to be less implicit.

Cypress configuration has been moved to the rool level as well. 

## Issue: Cypress path resolving

If run in a nested package's directory, Cypress will resolve the paths in the execution command relative to that directory (which is expected). Since Cypress configuration lives in the root, one needs to explicitly point to it:

```bash
$ cypress run -C ../../cypress.json
```

The Cypress configuration may set paths to various assets like `pluginsFile` or `supportFile`:

```
{
  "supportFile": "./cypress/support/index.js"
}
```

**However**, those path in `cypress.json` will be resolved _relatively to the `cwd`_ of the `cypress run` command. This is a nightmare, and to workaround this Cypress runs will be executed from the root level always:

```bash
$ (cd ../../ && cypress run ...)
```

> This also removes the need to specify the `cypress.json` config and let the paths in the config be relative to the `cypress.json` location.

**Comment by kettanaito** [comment]
Currently trying to build `@atomic-layout/emotion` into CJS module. See the status in the `emotion-build-cjs` job.

**Comment by kettanaito** [comment]
## CJS build

Got the CJS build working by properly configuring `tsconfig.json` to digest TypeScript modules referenced in `packages/atomic-layout`:

```json
{
  "compilerOptions": {
    "rootDirs": ["src", "../atomic-layout/src"]
  }
}
```

> That being sad, although CJS build is performed successfully, Storybook cannot build itself with that version of build. That may be both build and Storybook issue.

**Comment by kettanaito** [comment]
## Storybook 5.3 issue

Updating from `5.1.11` to `5.3.7` introduces some internal changes to Storybook that result into the following exception during its build:

```
Uncaught ReferenceError: exports is not defined
```

On the local such exception is represented in a different way:

```
WARNING in /Users/.../atomic-layout/examples/hooks/UseViewportChange.jsx 25:20-23
"export 'Box' was not found in 'atomic-layout'
```

> There is no connection between the error and the module origin. It warns on all named exports of the package.

**Comment by kettanaito** [comment]
Need to verify if those `globals` values for UMD build actually load up Emotion from the context.

**Comment by kettanaito** [comment]
Currently the size of UMD bundle of `@atomic-layout/emotion` exceeds the allowed limit of 10KB:

```
FAIL  lib/umd/index.js: 18.13KB > maxSize 10KB (gzip) 
```

I have a suspicion that happens due to `@emotion/core` and `@emotion/styled` not being excluded as globals properly.

**Comment by kettanaito** [comment]
# Alpha is published! 🎉

Install the alpha version of the package to use Atomic Layout with emotion!

```bash
yarn add @atomic-layout/emotion@0.12.0-alpha.1 @emotion/core @emotion/styled
```

@bitttttten, I would be very thankful if you could try to use the alpha version. Post any issues you find here and I'll look into them. At the same time I'd try to verify it on other projects too. Thank you!

**Pull request merged**
