### PR TITLE
Hooks: Introduces "useResponsiveValue" hook

### LINKED ISSUE #132: [RFC] Generic viewport-based API
## What

I propose to expose the API that automatically assigns the given value at the given breakpoint based on a prop name's suffix (which makes a responsive prop).

## Why

So that developers can create *any* responsive logic while being inline with the defined global breakpoints.

## Specification

1. The library exports a functional utility that produces breakpoint-based values from the given configuration:

```jsx
import { useResponsiveValue } from 'atomic-layout'

const value = useResponsiveValue({
  xs: 'value when on xs',
  md: 'value when on md',
}, 'default value, when neither')
```

2. The utility function's signature is as follows:

```ts
const useResponsiveValue = <T>(breakpointMap: Record<string, T>, defaultValue?: T) => T
```

3. The utility function analyzes the given breakpoint names from the Layout options, and finds the key-value pair which breakpoint is matched by the viewport.
3. In case viewport doesn't match any of the given breakpoints, `defaultValue` is returned, if present.

3. > (?) Support for custom breakpoint objects, not defined in the Layout options.

### PR DESCRIPTION
**Pull request by kettanaito**
# Change log

- Adds generic `withBreakpoints` util that resolves matching breakpoint value based on the breakpoint-value pairs
- Adds `useResponsiveValue` hook that allows to resolve viewport-based value of any type
- Adds generic `useViewportChange` hook
- Adds generic `useBreakpointChange` hook

# GitHub

- Closes #132

# Roadmap

- [x] Add `useResponsiveValue` hook
- [x] Add unit tests
- [x] Add integration tests
- [x] Ensure smooth value changes upon window resize transients
- [x] ~~Add memoization to viewport-value computation~~
- [x] Consider shorter API for convenience
- [ ] Consider support for custom media queries, apart from global breakpoints
- [x] Add tests for `useViewportChange` hook

### CODE REVIEW

**Comment by kettanaito** [comment]
I experience weird transitions between fast window resizes, need to investigate that to ensure calculation is memoized, and there is no visual artifacts between breakpoints change.

**Comment by Vidlec** [comment]
Maybe make it debounced, that would fix the quick resize issue

**Comment by kettanaito** [comment]
Great suggestion, @Vidlec!
I've debounced window resize handler and the behavior is smooth now.

https://github.com/kettanaito/atomic-layout/blob/b3eabbacfc802368872e5ca8924de18704686d7f/src/hooks/useResponsiveValue/index.ts#L11-L14

**Comment by kettanaito** [comment]
Currently each `useResponsiveValue` hook spawns its individual window resize listener. If this hook is meant to be used within #148, having per-prop resize listener is a huge overkill. I can think of the following ways to minimize the amount of listeners:

1. Introduce a generic `useViewportChange(callback)` hook that fires on debounced window resize and returns new viewport in the argument. Then `useResponsiveValue` can use this hook to rcheck breakpoints matches and resolve to the next value.
1. Change the input signature of `useResponsiveValue` hook or introduce a generic hook with the next signature:

```js
useResponsiveValues({
  valueName: {
    md: 'when md',
    lg: 'when lg',
  }
})
```

3. Do 1 and leave `useResponsiveValue` as is, only using `useViewportChange` internally. Then `useResponsiveProps` hook would also use `useViewportChange` in a combination with `withBreakpoints`.

**Comment by kettanaito** [comment]
`useResponsiveValue` now uses `useViewportChange` hook internally.

**Comment by kettanaito** [comment]
Regarding memoization. I do expect window resize to happen often, which implies values-breakpointName pairs should be memoized.

```js
const withBreakpoint = memoizeWith((args) => {
  return produceKeyFrom(args, breakpointName)
}, { md: 'foo' }, ...)
```

The same set of values on the known _breakpoint name_ should produce a memoized result. Breakpoint name plays a key note here, as different viewport dimensions may lie within the same breakpoint. This means breakpoint matching may be changed in `withBreakpoints` in order to use it for memoization key.

**Pull request merged**
