### PR TITLE
Fix default breakpoints to match bootstrap grid

### LINKED ISSUE #204: Default breakpoints sm, md, lg are off by 1px
## What:

Defaults are defined as

```
  breakpoints: {
    xs: {
      maxWidth: '575px',
    },
    sm: {
      minWidth: '576px',
      maxWidth: '768px',
    },
    md: {
      minWidth: '769px',
      maxWidth: '992px',
    },
    lg: {
      minWidth: '993px',
      maxWidth: '1199px',
    },
    xl: {
      minWidth: '1200px',
    },
  },
```

should be 

```
  breakpoints: {
    xs: {
      maxWidth: '575px',
    },
    sm: {
      minWidth: '576px',
      maxWidth: '767px',
    },
    md: {
      minWidth: '768px',
      maxWidth: '991px',
    },
    lg: {
      minWidth: '992px',
      maxWidth: '1199px',
    },
    xl: {
      minWidth: '1200px',
    },
  },
```

https://getbootstrap.com/docs/4.3/layout/overview/#responsive-breakpoints

### PR DESCRIPTION
**Pull request by slackday**
# Change log

- Adjusted breakpoints defaultOptions to match Bootstrap grid

# GitHub

- Closes #204

### CODE REVIEW

**Comment by kettanaito** [comment]
Looks great.

When running these changes on local there are 7 failing tests:

```
56 passing (50s)
  7 failing

  1) Only Custom breakpoints Renders children at the explicit breakpoint (for):
     CypressError: Timed out retrying: expected '<span#first.sc-htpNat.czOTGF>' not to be 'visible'
      at Object.cypressErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84573:11)
      at Object.throwErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84538:18)
      at Object.throwErrByPath (http://localhost:50770/__cypress/runner/cypress_runner.js:84565:17)
      at retry (http://localhost:50770/__cypress/runner/cypress_runner.js:77812:16)
      at http://localhost:50770/__cypress/runner/cypress_runner.js:69764:18
      at tryCatcher (http://localhost:50770/__cypress/runner/cypress_runner.js:133768:23)
      at Promise._settlePromiseFromHandler (http://localhost:50770/__cypress/runner/cypress_runner.js:131786:31)
      at Promise._settlePromise (http://localhost:50770/__cypress/runner/cypress_runner.js:131843:18)
      at Promise._settlePromise0 (http://localhost:50770/__cypress/runner/cypress_runner.js:131888:10)
      at Promise._settlePromises (http://localhost:50770/__cypress/runner/cypress_runner.js:131963:18)
      at Async._drainQueue (http://localhost:50770/__cypress/runner/cypress_runner.js:128692:16)
      at Async._drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128702:10)
      at Async.drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128576:14)

  2) Only Custom breakpoints Renders children up to a given breakpoint (to):
     CypressError: Timed out retrying: expected '<span#second.sc-htpNat.czOTGF>' not to be 'visible'
      at Object.cypressErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84573:11)
      at Object.throwErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84538:18)
      at Object.throwErrByPath (http://localhost:50770/__cypress/runner/cypress_runner.js:84565:17)
      at retry (http://localhost:50770/__cypress/runner/cypress_runner.js:77812:16)
      at http://localhost:50770/__cypress/runner/cypress_runner.js:69764:18
      at tryCatcher (http://localhost:50770/__cypress/runner/cypress_runner.js:133768:23)
      at Promise._settlePromiseFromHandler (http://localhost:50770/__cypress/runner/cypress_runner.js:131786:31)
      at Promise._settlePromise (http://localhost:50770/__cypress/runner/cypress_runner.js:131843:18)
      at Promise._settlePromise0 (http://localhost:50770/__cypress/runner/cypress_runner.js:131888:10)
      at Promise._settlePromises (http://localhost:50770/__cypress/runner/cypress_runner.js:131963:18)
      at Async._drainQueue (http://localhost:50770/__cypress/runner/cypress_runner.js:128692:16)
      at Async._drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128702:10)
      at Async.drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128576:14)

  3) Only Custom breakpoints Renders children starting from a given breakpoint (from):
     CypressError: Timed out retrying: Expected to find element: '#third', but never found it.
      at Object.cypressErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84573:11)
      at Object.throwErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84538:18)
      at Object.throwErrByPath (http://localhost:50770/__cypress/runner/cypress_runner.js:84565:17)
      at retry (http://localhost:50770/__cypress/runner/cypress_runner.js:77812:16)
      at http://localhost:50770/__cypress/runner/cypress_runner.js:69764:18
      at tryCatcher (http://localhost:50770/__cypress/runner/cypress_runner.js:133768:23)
      at Promise._settlePromiseFromHandler (http://localhost:50770/__cypress/runner/cypress_runner.js:131786:31)
      at Promise._settlePromise (http://localhost:50770/__cypress/runner/cypress_runner.js:131843:18)
      at Promise._settlePromise0 (http://localhost:50770/__cypress/runner/cypress_runner.js:131888:10)
      at Promise._settlePromises (http://localhost:50770/__cypress/runner/cypress_runner.js:131963:18)
      at Async._drainQueue (http://localhost:50770/__cypress/runner/cypress_runner.js:128692:16)
      at Async._drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128702:10)
      at Async.drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128576:14)

  4) Only Custom breakpoints Supports inclusive (bell) behavior:
     CypressError: Timed out retrying: expected '<span#fourth.sc-htpNat.czOTGF>' not to be 'visible'
      at Object.cypressErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84573:11)
      at Object.throwErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84538:18)
      at Object.throwErrByPath (http://localhost:50770/__cypress/runner/cypress_runner.js:84565:17)
      at retry (http://localhost:50770/__cypress/runner/cypress_runner.js:77812:16)
      at http://localhost:50770/__cypress/runner/cypress_runner.js:69764:18
      at tryCatcher (http://localhost:50770/__cypress/runner/cypress_runner.js:133768:23)
      at Promise._settlePromiseFromHandler (http://localhost:50770/__cypress/runner/cypress_runner.js:131786:31)
      at Promise._settlePromise (http://localhost:50770/__cypress/runner/cypress_runner.js:131843:18)
      at Promise._settlePromise0 (http://localhost:50770/__cypress/runner/cypress_runner.js:131888:10)
      at Promise._settlePromises (http://localhost:50770/__cypress/runner/cypress_runner.js:131963:18)
      at Async._drainQueue (http://localhost:50770/__cypress/runner/cypress_runner.js:128692:16)
      at Async._drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128702:10)
      at Async.drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128576:14)

  5) Only Custom breakpoints Supports exclusive (notch) behavior:
     CypressError: Timed out retrying: expected '<span#fifth.sc-htpNat.czOTGF>' not to be 'visible'
      at Object.cypressErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84573:11)
      at Object.throwErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84538:18)
      at Object.throwErrByPath (http://localhost:50770/__cypress/runner/cypress_runner.js:84565:17)
      at retry (http://localhost:50770/__cypress/runner/cypress_runner.js:77812:16)
      at http://localhost:50770/__cypress/runner/cypress_runner.js:69764:18
      at tryCatcher (http://localhost:50770/__cypress/runner/cypress_runner.js:133768:23)
      at Promise._settlePromiseFromHandler (http://localhost:50770/__cypress/runner/cypress_runner.js:131786:31)
      at Promise._settlePromise (http://localhost:50770/__cypress/runner/cypress_runner.js:131843:18)
      at Promise._settlePromise0 (http://localhost:50770/__cypress/runner/cypress_runner.js:131888:10)
      at Promise._settlePromises (http://localhost:50770/__cypress/runner/cypress_runner.js:131963:18)
      at Async._drainQueue (http://localhost:50770/__cypress/runner/cypress_runner.js:128692:16)
      at Async._drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128702:10)
      at Async.drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128576:14)

  6) Hooks useViewportChange Renders when viewport matches:
     CypressError: Timed out retrying: Expected to find element: '#element', but never found it.
      at Object.cypressErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84573:11)
      at Object.throwErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84538:18)
      at Object.throwErrByPath (http://localhost:50770/__cypress/runner/cypress_runner.js:84565:17)
      at retry (http://localhost:50770/__cypress/runner/cypress_runner.js:77812:16)
      at http://localhost:50770/__cypress/runner/cypress_runner.js:69764:18
      at tryCatcher (http://localhost:50770/__cypress/runner/cypress_runner.js:133768:23)
      at Promise._settlePromiseFromHandler (http://localhost:50770/__cypress/runner/cypress_runner.js:131786:31)
      at Promise._settlePromise (http://localhost:50770/__cypress/runner/cypress_runner.js:131843:18)
      at Promise._settlePromise0 (http://localhost:50770/__cypress/runner/cypress_runner.js:131888:10)
      at Promise._settlePromises (http://localhost:50770/__cypress/runner/cypress_runner.js:131963:18)
      at Async._drainQueue (http://localhost:50770/__cypress/runner/cypress_runner.js:128692:16)
      at Async._drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128702:10)
      at Async.drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128576:14)

  7) Recipes Grid template column supports dynamic column width:
     CypressError: Timed out retrying: expected '<div#content.sc-bdVaJa.iOHNWr>' to have CSS property 'width' with the value '543px', but the value was '542px'
      at Object.cypressErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84573:11)
      at Object.throwErr (http://localhost:50770/__cypress/runner/cypress_runner.js:84538:18)
      at Object.throwErrByPath (http://localhost:50770/__cypress/runner/cypress_runner.js:84565:17)
      at retry (http://localhost:50770/__cypress/runner/cypress_runner.js:77812:16)
      at http://localhost:50770/__cypress/runner/cypress_runner.js:69764:18
      at tryCatcher (http://localhost:50770/__cypress/runner/cypress_runner.js:133768:23)
      at Promise._settlePromiseFromHandler (http://localhost:50770/__cypress/runner/cypress_runner.js:131786:31)
      at Promise._settlePromise (http://localhost:50770/__cypress/runner/cypress_runner.js:131843:18)
      at Promise._settlePromise0 (http://localhost:50770/__cypress/runner/cypress_runner.js:131888:10)
      at Promise._settlePromises (http://localhost:50770/__cypress/runner/cypress_runner.js:131963:18)
      at Async._drainQueue (http://localhost:50770/__cypress/runner/cypress_runner.js:128692:16)
      at Async._drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128702:10)
      at Async.drainQueues (http://localhost:50770/__cypress/runner/cypress_runner.js:128576:14)
```

My first guess is that Cypress or end-to-end scenarios somehow use outdated values, therefore some assertions based on the viewport change fail. I will try to look at that, and if you have time you can peek into failed tests as well. I would appreciate your help.

**Comment by kettanaito** [comment]
I will try to solve things I found and publish a fix branch. Once it's done I would kindly ask you to rebase on that branch, which should make all the tests pass.

To verify the tests' status you can run the following commands:

```bash
yarn build:storybook # end-to-end tests are run agains built storybook
yarn test # runs unit and end-to-end tests
```

**Comment by kettanaito** [comment]
I've resolved all the misaligned tests. Could you please rebase upon `204-bootstrap-breakpoints-tests` branch?

```bash
git fetch origin
git checkout YOUR_BRANCH
git rebase 204-bootstrap-breakpoints-tests
git push # with "-f" if necessary
```

Once it's done the tests on your branch should all pass. Please confirm that and we can merge :) Thank you for contribution!

**Comment by slackday** [comment]
Thanks now the tests pass
```
Test Suites: 34 passed, 34 total
Tests:       189 passed, 189 total
Snapshots:   0 total
Time:        6.424s
Ran all test suites.
```

But Cypress has some errors in it's tests... I will look at it some more.

```
  ┌──────────────────────────┐
  │ Tests:        63         │
  │ Passing:      57         │
  │ Failing:      6          │
  │ Pending:      0          │
  │ Skipped:      0          │
  │ Screenshots:  6          │
  │ Video:        false      │
  │ Duration:     48 seconds │
  │ Spec Ran:     index.js   │
  └──────────────────────────┘
```

**Comment by kettanaito** [comment]
Thanks! Looks perfect.

That's not Storybook itself, but the way this project is set up: it tests against build instance of storybook during production tests. Therefore it requires to build storybook first, and then run cypress. You've figured that out by yourself, so it's post-factum explanation 😄

**Pull request merged**
