### PR TITLE
Update js dependencies

### PR DESCRIPTION
**Pull request by ruhaise**
updated dependencies of the project => including the main ones, react, styled components etc..

### CODE REVIEW

**Comment by ruhaise** [comment]
@kettanaito  please have a look on this PR => i have tried to update almost all dependencies, all test are passing also i had a quick look at everything and all seems ok

**Comment by kettanaito** [comment]
Thanks for the pull request!

Attempting to build Storybook on local, getting the following error message:

```
ERR! => Failed to build the manager
ERR! Module not found: Error: Can't resolve 'babel-loader' in '/Users/kettanaito/Projects/atomic-layout'
(node:1218) UnhandledPromiseRejectionWarning: ModuleNotFoundError: Module not found: Error: Can't resolve 'babel-loader' in '/Users/kettanaito/Projects/atomic-layout'
    at factory.create (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/Compilation.js:888:10)
    at factory (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/NormalModuleFactory.js:337:24)
    at /Users/kettanaito/Projects/atomic-layout/node_modules/neo-async/async.js:2830:7
    at /Users/kettanaito/Projects/atomic-layout/node_modules/neo-async/async.js:6877:13
    at /Users/kettanaito/Projects/atomic-layout/node_modules/neo-async/async.js:2830:7
    at done (/Users/kettanaito/Projects/atomic-layout/node_modules/neo-async/async.js:2925:13)
    at resolver.resolve (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/NormalModuleFactory.js:449:23)
    at doResolve (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:23:37)
    at hook.callAsync (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at args (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
    at hook.callAsync (/Users/kettanaito/Projects/atomic-layout/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

That's the error message of Storybook failing to resolve `babel-loader`, which it depends on. I'm not sure if it lists the package as a peer dependency, though. If it doesn't, it would be great to contribute to them to fix that behavior. 

> I wonder where did `babel-loader` dependency go from the Atomic Layout's dependencies. It was there for the sake of Storybook only.

**Comment by ruhaise** [comment]
I will have a look on it soon. I did the ‘prepublish’ command and everything was fine. Dont know whats happening now.

**Comment by kettanaito** [comment]
@ruhaise I usually use this sequence of commands to verify:

```bash
$ yarn install && yarn build && yarn build:storybook && yarn test
```

Let me know if that error is reproducible for you, or if you need any help. Thanks!

**Comment by kettanaito** [comment]
@ruhaise, thanks for updating the branch. Switching to it to investigate what's happening. I'd like this to be merged today.

**Comment by kettanaito** [comment]
I haven't found any info in the release notes of `storybook@5.2.6` that would explain the issue we are experiencing. They issue may also not be in Storybook itself, as it _does_ resolve the module, but states that the module does not export `Box` and other components.

```
WARN "export 'Composition' was not found in 'atomic-layout'
WARN     at HarmonyImportSpecifierDependency._getErrors (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:109:11)
WARN     at HarmonyImportSpecifierDependency.getWarnings (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:60:15)
WARN     at Compilation.reportDependencyErrorsAndWarnings (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/Compilation.js:1454:24)
WARN     at hooks.finishModules.callAsync.err (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/Compilation.js:1258:10)
WARN     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
WARN     at AsyncSeriesHook.lazyCompileHook (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/Hook.js:154:20)
WARN     at Compilation.finish (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/Compilation.js:1253:28)
WARN     at hooks.make.callAsync.err (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/Compiler.js:672:17)
WARN     at _done (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
WARN     at _err1 (eval at create (/Users/kettanaito/Projects/atomic-layout/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
WARN     at _addModuleChain (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/Compilation.js:1185:12)
WARN     at processModuleDependencies.err (/Users/kettanaito/Projects/atomic-layout/node_modules/webpack/lib/Compilation.js:1097:9)
WARN     at process._tickCallback (internal/process/next_tick.js:61:11)
WARN  @ ./examples/index.js
WARN  @ ./.storybook/config.js
WARN  @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js
```

Strangely, I'm not experiencing the `babel-loader` issue anymore.

**Comment by kettanaito** [comment]
It's been a breaking change of `cross-env` that broke the unit tests I've mentioned about. Also, the latest Storybook version requires `babel-loader` to be installed as a peer dependency. 

Closing in favor of https://github.com/kettanaito/atomic-layout/commit/aabebb18afe3e27345d6e63e05bf6e4ce1f12d37.

**Pull request closed without merging**
