### PR TITLE
Fix ref usage at useViewportChange cleanup

### LINKED ISSUE #232: Event listener leak in responsive hooks
## What:

It appears that all of the responsive hooks are subjected to the following issue:

Screen Shot 2019-10-05 at 12 10 09

This needs investigation and fix.

## Why:

Most likely the event listeners established in the hooks are not cleaned up properly when a component unmouts.

## Environment:

- atomic-layout version: `0.9.8`

## Steps to reproduce:

1. Open any story in Storybook under the "Other > Hooks" group.
1. Play around with the hook.
1. Switch to another hook story.
1. Try to resize the window. See the aforementioned error message in the console.

## Expected behavior:

- Event listeners are cleaned up after a component's unmounting
- No such error message in the browser's console

### PR DESCRIPTION
**Pull request by iwgx**
## Changes

I'm destructuring current from handleWindowResize ref 

## Before
before

## After
after

## GitHub

- Closes #232

### CODE REVIEW

**Comment by kettanaito** [comment]
Hello, @iwgx. Thank you for the fix!

Could you please explain me what was the reason behind the issue, and how did destructuring help? Was it something about the reference to the handler function?

**Comment by iwgx** [comment]
I think it's because

```jsx
useEffect(() =>
    handleWindowResize.current = throttle(callback, throttleInterval)
})
```

So every time a value is changed it's doing reassign of handleWindowResize.current with new reference. In the end when useEffect doing cleanup there is a possibility that now handleWindowResize.current is not same reference again

If you use eslint rule of `react-hooks/exhaustive-deps` you will get this warning like in CodeSandbox
warning in codesandbox

**Comment by silltho** [comment]
oh no! i worked on exactly the same issue and was just about to create a pull request :(. after some investigation i would say the problem was that handleResizeWindow was storing an anonymous function. 

image
https://www.w3schools.com/jsref/met_element_removeeventlistener.asp

this would be my solution:
```
  function handleResizeEvent() {
    handleWindowResize.current()
  }

  useEffect(() => {
    handleWindowResize.current = throttle(callback, throttleInterval)
  })

  useEffect(() => {
    handleResizeEvent()
    window.addEventListener('resize', handleResizeEvent)
    return () => {
      window.removeEventListener('resize', handleResizeEvent)
    }
  }, [])
```

but i have to say, I think the solution of @iwgx is better than mine.

**Comment by kettanaito** [comment]
Thank you for the insights, folks! Looks solid, approved.

**Comment by kettanaito** [comment]
Welcome to contributors, @iwgx! 🎉

**Pull request merged**
